### ISSUE TITLE
Error Running PaGeSearch with Keras (Empty batch_outputs)

### ISSUE THREAD

**Issue by ghost** [Sohyoung/PaGeSearch#1]
Hello,

I'm encountering an error while running PaGeSearch, and I'd appreciate some help in resolving it.

### Context

I'm running PaGeSearch with the following command:

`
python ~/PaGeSearch/Codes/pagesearch.py -g ~/PaGeSearch/genome/Gobio_gobio_genome.fa -p ~/PaGeSearch/gene_sequences_defensome/ -od ~/Projet_3/Pipeline_B -op output_pagesearch -s zebrafish -t 37
`
### Problem Details

The error message displayed in the console is as follows:

"""
Start PaGeSearch

Genome assembly at: /data/home/jdutel/PaGeSearch/genome/Gobio_gobio_genome.fa
Query gene sequences at: /data/home/jdutel/PaGeSearch/gene_sequences_defensome
Archetype species: zebrafish
Results will be saved at: /data/home/jdutel/Projet_3/Pipeline_B/test_serious.txt
Using 37 threads

Candidate region identification through sequence similarity search
Candidate region grouping and extension
Making protein hints
looking up hostname: Success
Ab initio gene prediction
Protein sequence alignment
looking up hostname: Success
Results filtering
Traceback (most recent call last):
  File "/data/home/jdutel/PaGeSearch/Codes/pagesearch.py", line 672, in <module>
    main(sys.argv)
  File "/data/home/jdutel/PaGeSearch/Codes/pagesearch.py", line 663, in main
    runPipeline(args.genome, args.pathway_gene_dir, args.outdir, args.outprefix, args.modelspecies, args.nthreads)
  File "/data/home/jdutel/PaGeSearch/Codes/pagesearch.py", line 600, in runPipeline
    filterResults(summary_fname, model_path)
  File "/data/home/jdutel/PaGeSearch/Codes/pagesearch.py", line 417, in filterResults
    df_tmp['Pred_prob'] = model.predict(X)
  File "/data/home/jdutel/anaconda3/envs/PaGeSearch_env/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/data/home/jdutel/anaconda3/envs/PaGeSearch_env/lib/python3.10/site-packages/keras/engine/training.py", line 2375, in predict
    raise ValueError(
ValueError: Unexpected result of `predict_function` (Empty batch_outputs). Please use `Model.compile(..., run_eagerly=True)`, or `tf.config.run_functions_eagerly(True)` for more information of where went wrong, or file an issue/bug to `tf.keras`.
"""

### Additional Information

I have attempted reinstalling Keras 2.11.0 and TensorFlow 2.11.0 in my Conda environment, but the error persists. It seems to be related to an empty batch being passed during the prediction step, but I’m not sure how to resolve it in the context of the PaGeSearch pipeline.

Any insights or suggestions would be greatly appreciated!

Thank you in advance.

**Comment by ghost** [comment]
Hello,

I wanted to provide an update on the issue I previously reported. I discovered that the error was due to the gene IDs being interpreted as unusual tuples, for instance, ('HSP70',). This caused issues during DataFrame joins, as it prevented matching the gene IDs correctly.

To resolve this, I extracted just the gene name within the tuple (e.g., HSP70), removing the extra characters like parentheses and commas. This adjustment allowed the DataFrames to match as expected.

I hope this helps anyone encountering similar issues!

**Comment by Sohyoung** [comment]
Hello.

Thank you for sharing your issues.


Regards,
Sohyoung

2024년 11월 12일 (화) 오후 7:27, jdutel ***@***.***>님이 작성:
